### ISSUE TITLE
0.58.1 build problem

### ISSUE THREAD

**Issue by tophf** [openstyles/stylus-lang-bundle#16]
@eight04, WDYT? 0.58.1 build fails because the new version of its `debug` dependency is apparently broken: the output (if I disable terser) sets the properties of `_module_exports_$1` first, then initializes it as `const _module_exports_$1 = setup(_module_exports_$1);` which of course is impossible to compile.

**Comment by eight04** [comment]
I think we can exclude the `debug` package using `shimEmpty`:
https://github.com/openstyles/stylus-lang-bundle/blob/17c484c090cbafda43e21efa57aed5c1a8082916/rollup.config.js#L27-L30

```js
shimEmpty([
  ...
  "debug"
]);
```
