### ISSUE TITLE
Compilation error Unconverted `require`

### ISSUE THREAD

**Issue by gitfei1231** [openstyles/stylus-lang-bundle#20]
`
(!) Plugin rollup-plugin-cjs-es: Unconverted `require`
node_modules/stylus/lib/utils.js: (132:15)
130:       return /\.styl$/i.test(dir) ? exports.lookupIndex(dir, paths, filename) : lookupPackage(dir + '.styl');
131:     }
132:     var main = require(relative(__dirname, pkg)).main;
                    ^
133:     if (main) {
134:       found = exports.find(join(dir, main), paths, filename);
node_modules/stylus/lib/functions/use.js: (29:11)
27:
28:   // use
29:   var fn = require(path.resolve(found));
               ^
30:   if ('function' != typeof fn) {
31:     throw new Error('plugin "' + plugin + '" does not export a function');
(!) Plugin rollup-plugin-cjs-es: util is not loaded.
created dist/stylus-renderer.min.js in 5.1s

`

**Comment by eight04** [comment]
It's not an error but a warning.
